packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
minimumReleaseAgeExclude:
  - '@expo/cli@56.1.19'
  - '@expo/config-plugins@56.0.12'
  - '@expo/fingerprint@0.19.7'
  - '@expo/prebuild-config@56.0.19'
  - '@expo/router-server@56.0.16'
  - babel-preset-expo@56.0.17
  - expo-asset@56.0.19
  - expo-modules-autolinking@56.0.19
  - expo-modules-core@56.0.20
  - expo-modules-jsi@56.0.12
  - expo@56.0.15
  - expo-build-properties@56.0.22
  - expo-location@56.0.20
  - expo-notifications@56.0.20
settings:
  nodeLinker: hoisted
